			installPartial: "部分插件已安装。重启后加载成功的项；找不到的请到插件市场搜索，或用 dsh plugin add。",
			installMissing: "目录里找不到这个包。请到插件市场搜索，或用 dsh plugin add。",
			installError: "无法安装推荐插件。",
			catalogTitle: "插件目录",
			catalogBody: "优先选用公司内部目录源（company-1024store）；若 Host 尚未注册该源，则回退到公开 DSH 1024Store。不会开机自动选用。",
			addCatalog: "添加并选用公司目录（或 1024Store）",
			catalogReady: "已选用目录源。可在上面一键安装推荐包，或打开“插件市场”标签搜索其他包名。",
			catalogBusy: "正在添加目录来源…",
			catalogError: "无法添加目录来源。请到“插件市场 > 来源”手动添加。",
			catalogUsingFallback: "公司目录源尚未注册，已回退到公开 1024Store。"
		};
		const en = {
			nav: "Example Company",
			pagesNav: "Example Company pages",
			tabBuiltin: "Built-in",
			tabEnterprise: "Enterprise",
			tabCurated: "Featured",
			intro: "Travels with the company plugin: Built-in identity, Enterprise pack, and Featured recommendations. Nothing installs at launch. Featured prefers the company catalog source and falls back to public 1024Store.",
			generalTitle: "General",
			identityTitle: "Organization display name",
			identityDesc: "Display name for the example company child. Real deployments wire SSO here; do not put secrets in the package.",
			ssoTitle: "SSO extension point",
			ssoDesc: "Idle example: no organization id and no embedded secrets.",
			ssoIdle: "Idle (not connected)",
			enterpriseTitle: "Enterprise",
			companyPackTitle: "Optional Company Pack",
			companyPackBody: "The Company Pack ships in the app graph but is not enabled by default and never silent-preinstalls at launch. Confirming enables the pack and company children, and may cascade recommended community plugins. Continue installs under Featured on the same page. Do not put secrets in the package.",
			pluginCompanyPack: "Optional Company Pack: example company child plus recommended community plugins. Install only after confirm.",
			installCompanyPack: "Install Company Pack…",
			confirmCompanyPackTitle: "Confirm Company Pack install",
			confirmCompanyPackBody: "This enables the Company Pack and company children, then installs the community recommendations below. Nothing installs at launch.",
			confirmCompanyPack: "Confirm install",
			cancelCompanyPack: "Cancel",
			companyPackRecommendationsHint: "Pack enabled. Workspace / office IM / narrow-screen recommendations are under Featured on this page.",
			curatedTitle: "Featured",
			pluginsTitle: "Recommended workspace plugins",
			pluginsBody: "These community plugins are not preinstalled. Install the recommended workspace pack in one click, or install one plugin at a time. Installs go through Plugin market verification and need a restart before Loader picks them up.",
			pluginWorkspaceShell: "Sidebar workbench for files, terminal, Git, and subagents.",
			pluginWorkspaceContext: "Context insight: category mix, compaction events, and the /context command.",
			officeImTitle: "Recommended office IM",
			officeImBody: "The starting point is official DingTalk Stream and the official WeCom AI Bot. That is a recommendation, not an allowlist. Feishu, aggregators, and other community channels still install from the Plugin market or dsh plugin add. Recommendations are not preinstalled. Put credentials in the plugin config or the local credential store; do not commit secrets.",
			pluginOfficeDingtalk: "Official DingTalk Stream: internal-app robot, Client ID + Secret, outbound network only — no public callback.",
			pluginOfficeWecom: "Official WeCom AI Bot: Bot ID + Secret over the official WebSocket long connection — no public callback.",
